name: instagram_clone
description: An Instagram clone using Flutter

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  bloc: ^9.0.0
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.6.8
  collection: ^1.19.1
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  envied: ^1.1.1
  equatable: ^2.0.7
  firebase_auth: ^5.5.4
  firebase_core: ^3.13.1
  firebase_storage: ^12.4.6
  flutter_bloc: ^9.1.1
  flutter_cache_manager: ^3.4.1
  flutter_displaymode: ^0.6.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.1.0
  get_it: ^8.0.3
  go_router: ^15.1.2
  json_annotation: ^4.9.0
  json_serializable: ^6.9.5
  logger: ^2.5.0
  material_design_icons_flutter: ^7.0.7296
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  bloc_test: ^10.0.0
  build_runner: ^2.4.15
  envied_generator: ^1.1.1
  flutter_lints: ^5.0.0
  lints: ^5.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Italic.ttf
          style: italic
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-BoldItalic.ttf
          style: italic
          weight: 700
    - family: Billabong
      fonts:
        - asset: assets/fonts/Billabong.ttf
