name: instagram_clone
description: An Instagram clone using Flutter

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.3.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  go_router: ^13.2.0
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.1
  firebase_core: ^2.25.4
  cloud_firestore: ^4.15.5
  flutter_displaymode: ^0.6.0
  equatable: ^2.0.5
  firebase_auth: ^4.17.5
  firebase_storage: ^11.6.6
  shared_preferences: ^2.2.2
  logger: ^2.0.2+1
  material_design_icons_flutter: ^7.0.7296
  flutter_native_splash: ^2.3.10
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  lints: ^3.0.0
  build_runner: ^2.4.8
  bloc_test: ^9.1.6

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Italic.ttf
          style: italic
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-BoldItalic.ttf
          style: italic
          weight: 700
    - family: Billabong
      fonts:
        - asset: assets/fonts/Billabong.ttf
