name: instagram_clone
description: An Instagram clone using Flutter

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  go_router: ^13.0.1
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.1
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  flutter_displaymode: ^0.6.0
  equatable: ^2.0.5
  firebase_auth: ^4.16.0
  provider: ^6.1.1
  flutter_spinkit: ^5.2.0
  shared_preferences: ^2.2.2
  logger: ^2.0.2+1
  material_design_icons_flutter: ^7.0.7296
  flutter_native_splash: ^2.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  lints: ^3.0.0
  build_runner: ^2.4.8

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-BoldItalic.ttf
          style: italic
          weight: 700
    - family: Billabong
      fonts:
        - asset: assets/fonts/Billabong.ttf
