name: instagram_clone
description: An Instagram clone using Flutter

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  go_router: ^14.1.4
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.2
  firebase_core: ^3.0.0
  cloud_firestore: ^5.0.0
  flutter_displaymode: ^0.6.0
  equatable: ^2.0.5
  firebase_auth: ^5.0.0
  firebase_storage: ^12.0.0
  shared_preferences: ^2.2.3
  logger: ^2.3.0
  material_design_icons_flutter: ^7.0.7296
  flutter_native_splash: ^2.4.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  lints: ^4.0.0
  build_runner: ^2.4.11
  bloc_test: ^9.1.7

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Italic.ttf
          style: italic
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-BoldItalic.ttf
          style: italic
          weight: 700
    - family: Billabong
      fonts:
        - asset: assets/fonts/Billabong.ttf
